services:
  db:
    image: postgres:15
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    container_name: db_app
    environment:
      APP_MODE: prod
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_project
    command: ["/bin/bash", "./docker_cmds/app.sh"]
    env_file:
      - .env
    ports:
      - "${DEPLOY_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      # Для постоянного хранения логов приложения (опционально)
      - app_logs:/test_project/app/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  db_data:
  app_logs:
